export const API = {
  API_URL: 'http://localhost:8000/api/v1/',

  AUTHENTICATION_SHOE_CHECK_URL: '',
  AUTHENTICATION_SHOE_NAME_CHECK_URL: '',
  AUTHENTICATION_SHOE_AUTHENTICITY_CHECK_URL: '',
  SOLE_CHECK_URL: '',

  INSTA_SEARCH_URL: '',

  DELPHI_FORCAST_URL: ''
};
